steps:
    - 
        id: "Rodando teste"
        name: 'gcr.io/cloud-builders/go:alpine'
        args: ['test', 'soma']

    - 
        id: "Buidando imagem"
        name: 'gcr.io/cloud-builders/docker'
        args: ['build', '--tag=gcr.io/$PROJECT_ID/go-soma', '.']

    - 
        id: "Rodando soma"
        name: 'gcr.io/cloud-builders/docker'
        args: ['run', 'gcr.io/$PROJECT_ID/go-soma']
    
images: ['gcr.io/$PROJECT_ID/go-soma:latest'] 
tags: ['cloud-builders-community']

